ARTIFACTS_DIR: "artifacts"
MODEL:
  in_ch: 3
  base_ch: 32
  group_norm_ch: 32
  ch_scalings: [1, 2, 4, 8]
  t_dim: 128
  T: 1000
  beta_1: 0.001
  beta_T: 0.02
DATA:
  dataset: CIFAR10Dataset
  root_dir: "data/cifar10"
  batch_size: 32
  img_size: [3, 32, 32]
MISC:
  n_denoise_imgs: 1
  plot_every_t_steps: 100
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  max_eval_iters: 25
  save_ckpt_every: 1
  eval_every: 1
  gradient_clip: null
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
